[package]
name = "lemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "robota"
path = "src/robota.rs"

[[bin]]
name = "robotb"
path = "src/robotb.rs"

[dependencies]
client = { path = "../transport/client", features = ["coprocessor"] }
common = { path = "../transport/common" }
protocol = { path = "../transport/vex/protocol" }

robot_algorithms = { git = "https://github.com/nonl4331/robot-algorithms" }

uom = "0.35"
log = "0.4"
dotenvy = "0.15"
anyhow = "1.0"
ringbuffer = "0.15"

bno055 = { version = "0.3.3", features = ["std"] }
embedded-hal = { version = "0.2.7", features = ["unproven"] }
rerun = { version = "0.10.1", default_features = false, features = ["log", "sdk"] }
rppal = { version = "0.14.1", features = ["hal-unproven"] }

[profile.dev]
strip = "debuginfo"
