[package]
name = "lemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "robota"
path = "src/robota.rs"

[[bin]]
name = "robotb"
path = "src/robotb.rs"

[dependencies]
client = { git = "ssh://git@github.com/EMU5-Robotics/transport", rev = "cab298a55192cf496576b127a459629c3666e4d4", features = ["coprocessor"] }
common = { git = "ssh://git@github.com/EMU5-Robotics/transport", rev = "cab298a55192cf496576b127a459629c3666e4d4" }
protocol = { git = "ssh://git@github.com/EMU5-Robotics/transport", rev = "cab298a55192cf496576b127a459629c3666e4d4" }
communication = { git = "ssh://git@github.com/EMU5-Robotics/communication", rev = "a638833372fc62e423bff4708eafbde942872b66" }

anyhow = "1.0"
log = "0.4"

[profile.dev]
strip = "debuginfo"
