[package]
name = "lemon"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../transport/client", features = ["coprocessor"] }
protocol = { path = "../transport/vex/protocol"  }


log = "0.4"
chrono = "0.4"
fern = { version = "0.6", features = ["colored"] }
